# Generated by Django 5.0 on 2023-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
